name: Build and Deploy TiddlyWiki

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '11'

      - name: Install TiddlyWiki5
        run: |
          git clone --depth 1 https://github.com/Jermolene/TiddlyWiki5.git
          cd TiddlyWiki5
          npm install
          npm link
          cd ..

      - name: Build TiddlyWiki
        run: tiddlywiki --verbose --build index

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
